spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration
  profiles:
     active: native
server:
  port: ${port:8888}

logging.file: ${java.io.tmpdir}/config.log